
# This file is autogenerated by update.py

@ stub -version=0x602+ CreateFileMappingFromApp
@ stdcall CreateFileMappingW() kernel32.CreateFileMappingW
@ stub -version=0x603+ DiscardVirtualMemory
@ stdcall FlushViewOfFile() kernel32.FlushViewOfFile
@ stdcall GetLargePageMinimum() kernel32.GetLargePageMinimum
@ stdcall GetProcessWorkingSetSizeEx() kernel32.GetProcessWorkingSetSizeEx
@ stdcall GetWriteWatch() kernel32.GetWriteWatch
@ stdcall MapViewOfFile() kernel32.MapViewOfFile
@ stdcall MapViewOfFileEx() kernel32.MapViewOfFileEx
@ stub -version=0x602+ MapViewOfFileFromApp
@ stub -version=0x603+ OfferVirtualMemory
@ stub -version=0xA00+ OpenFileMappingFromApp
@ stdcall OpenFileMappingW() kernel32.OpenFileMappingW
@ stdcall ReadProcessMemory() kernel32.ReadProcessMemory
@ stub -version=0x603+ ReclaimVirtualMemory
@ stdcall ResetWriteWatch() kernel32.ResetWriteWatch
@ stub -version=0xA00+ SetProcessValidCallTargets
@ stdcall SetProcessWorkingSetSizeEx() kernel32.SetProcessWorkingSetSizeEx
@ stdcall UnmapViewOfFile() kernel32.UnmapViewOfFile
@ stub -version=0x602+ UnmapViewOfFileEx
@ stdcall VirtualAlloc() kernel32.VirtualAlloc
@ stub -version=0xA00+ VirtualAllocFromApp
@ stdcall VirtualFree() kernel32.VirtualFree
@ stdcall VirtualFreeEx() kernel32.VirtualFreeEx
@ stdcall VirtualLock() kernel32.VirtualLock
@ stdcall VirtualProtect() kernel32.VirtualProtect
@ stub -version=0xA00+ VirtualProtectFromApp
@ stdcall VirtualQuery() kernel32.VirtualQuery
@ stdcall VirtualQueryEx() kernel32.VirtualQueryEx
@ stdcall VirtualUnlock() kernel32.VirtualUnlock
@ stdcall WriteProcessMemory() kernel32.WriteProcessMemory
