
# This file is autogenerated by update.py

@ stub -version=0x0A00+ CopyFileFromAppW
@ stub -version=0x0A00+ CreateDirectoryFromAppW
@ stub -version=0x0A00+ CreateFile2FromAppW
@ stub -version=0x0A00+ CreateFileFromAppW
@ stub-version=0x0A00+  DeleteFileFromAppW
@ stub -version=0x0A00+ FindFirstFileExFromAppW
@ stub -version=0x0A00+ GetFileAttributesExFromAppW
@ stub -version=0x0A00+ MoveFileFromAppW
@ stub -version=0x0A00+ RemoveDirectoryFromAppW
@ stub -version=0x0A00+ ReplaceFileFromAppW
@ stub -version=0x0A00+ SetFileAttributesFromAppW
