
# This file is autogenerated by update.py

@ stub -version=0x602+ AppContainerDeriveSidFromMoniker
@ stub -version=0x602+ AppContainerFreeMemory
@ stub -version=0x602+ AppContainerLookupDisplayNameMrtReference
@ stub -version=0x602+ AppContainerLookupMoniker
@ stub -version=0x602+ AppContainerRegisterSid
@ stub -version=0x602+ AppContainerUnregisterSid
@ stub -version=0x602+ AppXFreeMemory
@ stub -version=0x602+ AppXGetApplicationData
@ stub -version=0x602+ AppXGetDevelopmentMode
@ stub -version=0x602+ AppXGetOSMaxVersionTested
@ stub -version=0x602+ AppXGetOSMinVersion
@ stub -version=0x602+ AppXGetPackageCapabilities
@ stub -version=0x602+ AppXGetPackageSid
@ stub -version=0x602+ AppXGetPackageState
@ stub -version=0x602+ AppXLookupDisplayName
@ stub -version=0x602+ AppXLookupMoniker
@ stub -version=0x602+ AppXSetPackageState
